### ISSUE TITLE
[BUG] `setZoomLevel` throws and fail the capture session on Android

### ISSUE THREAD

**Issue by a1239897580** [fluttercandies/flutter_wechat_camera_picker#104]
**Describe the bug**

调用相机录制安卓端白屏ios端闪退
**How to reproduce**

final AssetEntity? entity = await CameraPicker.pickFromCamera(
      Get.context!,
      pickerConfig: CameraPickerConfig(
          enableRecording: true,
          onlyEnableRecording: false,
          maximumRecordingDuration: const Duration(seconds: 60)
      ),
    );

1.正常调用相机,进行录制。这是必现问题
2.在安卓端,他的表现行为是白屏,长安开启录屏后控制台报异常。
3.在ios端,首次可以正常使用,没有问题,录制完成再次调用方法进行录制的时候发生闪退

**Expected behavior**

**Screenshots (If contains)**

android 长按录制中的错误
![image](https://user-images.githubusercontent.com/70512922/174571373-b353f781-47c1-4f0e-895e-cd0cbedfc467.png)
android 长按结束的错误
![image](https://user-images.githubusercontent.com/70512922/174571270-82570b98-bcb9-4487-b655-497d406f3081.png)
ios端表现为闪退,疑似内存过大被系统kill,在控制台看到打开相机的瞬间申请了300+内存

**Version information**

- Device: 任何android与ios
- OS: 安卓似乎仅安卓8及以下有此问题。ios设备好像都存在这个问题
- Package Version: ^3.2.0+1
- Flutter Version: 2.10.5

**Additional context**

**Comment by AlexV525** [comment]
> * Device: 任何android与ios
> * OS: 安卓似乎仅安卓8及以下有此问题。ios设备好像都存在这个问题

嗯，张口就来。

请测试官方 `camera` 后再次补充信息。

**Comment by a1239897580** [comment]
我测试了官网camera，是没有问题的。

**Comment by a1239897580** [comment]
我不否认可能是我的代码存在问题,但是这个问题他确实是存在的，在安卓8以下。长按开始录制的时候他的表现形式为
![image](https://user-images.githubusercontent.com/70512922/174928115-6333f26c-c336-47af-ac62-313cb2b3c059.png)
长按停止的时候是这样的
![image](https://user-images.githubusercontent.com/70512922/174928182-62e90061-bb65-4e79-be33-29231f65dce1.png)

**Comment by AlexV525** [comment]
测试 camera 在你的设备上是否支持缩放，根据报错是缩放时错误导致没有成功开始录制。

**Comment by a1239897580** [comment]
可以进行缩放,缩放功能没有问题

**Comment by a1239897580** [comment]
1655891563057822.mp4

**Comment by a1239897580** [comment]
https://user-images.githubusercontent.com/70512922/175000770-cd09387b-23fa-4184-b76e-b6195e3087db.mp4

**Comment by a1239897580** [comment]
好吧,官方相机也不行,两个插件的表现形式是一样的，开始之后画面就卡死了。我似乎该去官方摄像机那边去反馈😪

**Comment by AlexV525** [comment]
> 好吧,官方相机也不行,两个插件的表现形式是一样的，开始之后画面就卡死了。我似乎该去官方摄像机那边去反馈😪

晚上尝试优化一下

**Comment by AlexV525** [comment]
尝试使用 #107 后再次测试。

**Comment by a1239897580** [comment]
#107 测试结果没有变化,报错与昨天一致,在该设备上调用setZoomLevel报错被捕捉。
![image](https://user-images.githubusercontent.com/70512922/175190465-d6406de2-8e95-45b3-9433-9fec0b5dbedf.png)

**Comment by a1239897580** [comment]
我尝试直接return不调用该方法，虽然没有报错被捕捉，但是任然无法录制，长按开始后画面卡住不动。
该设备还有另一个问题，在结束后调用videoController.initialize()出错被捕捉
![image](https://user-images.githubusercontent.com/70512922/175192043-50e30e41-f72d-4bae-b210-fe773c6c62af.png)
![image](https://user-images.githubusercontent.com/70512922/175192235-d4f3a7f9-4623-45ae-8da7-c6bc3c37ba5d.png)

**Comment by AlexV525** [comment]
请在官方 repo 提出 issue 并链接到此，提供迄今为止的完整且准确的信息。
