### ISSUE TITLE
Custom UI / customUIBuilder

### ISSUE THREAD

**Issue by jtkeyva** [fluttercandies/flutter_wechat_camera_picker#112]
**Version information**
N/A

**Is your feature request related to a problem?**

No problem, except you can't change the look/feel.

**Describe the solution you'd like**

A way to customize the UI and gestures. Could be as simple as cloning the foregroundBuilder into a customUIBuilder function and having an option to disable the hardcoded baked in UI. A demo theme utilizing all functions such as shootingButton, backButton, flash, switch camera, close etc would be ideal.

**Describe alternatives you've considered**

Forking or hacking at the source code and hardcoding the changes.

**Additional context**

Perhaps this decouples the "WeChat" portion so a new package name like customCameraPicker or something could also work.

**Comment by AlexV525** [comment]
Would a similar [delegate mechanism implemented in wechat_assets_picker](https://github.com/fluttercandies/flutter_wechat_assets_picker#using-custom-delegate) helps?

**Comment by jtkeyva** [comment]
I believe so. Essentially, it would be nice to be able to control the underlying functions/methods so I can put what ever icon, image, text etc on the screen and create buttons for them. Seems like it could almost all happen in the foregroundBuilder if you opened up the methods?

**Comment by AlexV525** [comment]
> Seems like it could almost all happen in the foregroundBuilder if you opened up the methods?

The `foregroundBuilder` is unable to carry this much content. We'll need to create delegations for it.

**Comment by jtkeyva** [comment]
ah i see

**Comment by AlexV525** [comment]
TBH, it's better to build from the camera package if you want a customized interface.

**Comment by jtkeyva** [comment]
> TBH, it's better to build from the camera package if you want a customized interface.

Yeah, kind of what I was thinking as well but you did a lot of the heavy lifting and came up with clever solutions to common problems. Thanks for the update :)
