### ISSUE TITLE
Video Recording Error

### ISSUE THREAD

**Issue by hateshkumar** [fluttercandies/flutter_wechat_camera_picker#121]
Right after finishing, I am facing an issue. 

Here is the code snap

<img width="803" alt="Screen Shot 2022-08-04 at 7 26 10 PM" src="https://user-images.githubusercontent.com/18635520/182871782-8be494e4-a21a-477d-8570-377893132ba8.png">

Error when initializing video controller: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

<img width="1450" alt="Screen Shot 2022-08-04 at 7 23 00 PM" src="https://user-images.githubusercontent.com/18635520/182871285-8386dde8-0048-4d8a-a3f7-d13fb0fe65c0.png">

**Comment by AlexV525** [comment]
#31
