### ISSUE TITLE
[Feature] Can you not save the picture in the album?

### ISSUE THREAD

**Issue by lnd1992** [fluttercandies/flutter_wechat_camera_picker#128]
**Version information**
 - Device: *e.g. iPhone SE2*
 - OS: *e.g. iOS 15.6.1*
 - Package Version: *e.g. v2.4.1*
 - Flutter Version: *e.g. v2.5.0*

I don't want to take the pictures or keep the recorded video in the album

**Comment by AlexV525** [comment]
Use `onEntitySaving` to hook your own implementation.

**Comment by sydneyagcaoili** [comment]
Want to bump this issue up. In iOS, saving the camera in a public folder causes it to be uploaded to iCloud for those who turned it on. This is a security issue. I wasn't able to make the **onEntitySaving** solve the issue. Any suggestion?

**Comment by AlexV525** [comment]
> I wasn't able to make the **onEntitySaving** solve the issue.

Information like this won't bring too much help for me to identify what's your intention and if any issues happened. Please seek your solution in the document, the example, or otherwise file a new issue.
