### ISSUE TITLE
[Feature] Multiple Camera handling

### ISSUE THREAD

**Issue by kareldb** [fluttercandies/flutter_wechat_camera_picker#134]
**Is your feature request related to a problem?**
Tested with iPhone.
If you switch camera’s, on first press it shows the front camera. If pressed again, it shows the ultrawide. On third it shows the normal camera.

As a user, I would expect switching cameras would mean switching from back to front. (And not switching between all possible cameras).

**Describe the solution you'd like**
The solution Apple camera uses for this. Above the record button: a 0.5 and 1x zoom option. 

![2E516898-86DF-4FF4-A780-A536623925C3](https://user-images.githubusercontent.com/83468355/191372954-b30ebe8e-f417-4f7e-84f9-56267e006387.jpeg)

**Comment by AlexV525** [comment]
Based on the features of the `camera` plugin, we might not be able to implement this. Can you check if it's doable in the `camera`'s example?

**Comment by kareldb** [comment]
@AlexV525 
The availableCameras function has a few properties
https://pub.dev/documentation/camera_fix_exception/latest/camera/availableCameras.html

I would suggest using the: lensDirection property to switch between the back and front camera.
This would solve the issue that the switch camera button is looping trough all the available cameras.

There's also a name property. Maybe we could use this to detect which camera is the 0,5 x and the 3 x for example.
I could test which value it returns on Apple devices, but I don't have an android device available at the moment.

**Comment by AlexV525** [comment]
I've already tested today that you cannot switch between cameras when a recording is processing. Otherwise, the recording will stop. So switching cameras when recording seems not doable at present.

Regarding 0.5x and 1x camera switching, it's already been supported by the plugin.

**Comment by kareldb** [comment]
Thanks. 
The switching during recording is currently being implemented in a pull request in the camera plugin. So hopefully later this year, this feature will be available.

https://github.com/flutter/plugins/pull/6478/

This is feature request is meant to select a camera before recording.

**Comment by AlexV525** [comment]
> Thanks. The switching during recording is currently being implemented in a pull request in the camera plugin. So hopefully later this year, this feature will be available.

Good to hear, I've subscribed to the request and we can leave this issue as a tracker too.

**Comment by AlexV525** [comment]
Oh we should use another issue for this. For switching cameras as an apple-like behavior, you can build your own `CameraPickerState`
