### ISSUE TITLE
[Feature] Can I just enable the back camera and hide the front and back camera switch on the page?

### ISSUE THREAD

**Issue by ehangwork** [fluttercandies/flutter_wechat_camera_picker#138]
**Version information**
 - Device: *e.g. iPhone 14*
 - OS: *e.g. iOS 16.0.2*
 - Package Version: *e.g. v3.3.3*
 - Flutter Version: *e.g. v2.17.0*

Can I just enable the back camera and hide the front and back camera switch on the page?

**Comment by AlexV525** [comment]
You can achieve this by creating your own `CameraPickerState` for the camera picker.
https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/51dd012ac3cacfd9587065e0fc1f888713f613d0/lib/src/widgets/camera_picker.dart#L34-L36
