### ISSUE TITLE
"Flash / bright screen" on front face camera while recording video

### ISSUE THREAD

**Issue by kareldb** [fluttercandies/flutter_wechat_camera_picker#142]
**Version information**
 - Device: iPhone 11
 - OS: IOS 16.0.0
 - Package Version: 3.6.3

**Is your feature request related to a problem?**
A possibility to also provide a "flash aka bright screen" while recording video in low light with the front facing camera. Just like the current behaviour with photo.

**Describe the solution you'd like**
A mechanism that auto detects if there's a low light situation (front camera) & than triggers a bright screen when recording front camera video.

I tought of:
- setting device brightness to max
- providing a white container (with opacity) during the recording of the front facing camera

**Comment by AlexV525** [comment]
This is implementable with a custom camera picker state. Providing an extra callback or prediction will increase the complexity of the package.

**Comment by kareldb** [comment]
@AlexV525 I understand it will create extra complexity to the package. 
But for the end users, it’s confusing, there is ambient light for lighting photo’s & not for video’s when using selfie camera in low light.

This because Snapchat, Instagram & iPhone camera implement this auto detect low light feature when recording selfie video.

Implementing this as a callback would indeed be over complex, because it’s so specific (selfie camera video record when low light).

**Comment by AlexV525** [comment]
As I said:

> This is implementable with a custom camera picker state.
