### ISSUE TITLE
Preload photo / video on capture

### ISSUE THREAD

**Issue by kareldb** [fluttercandies/flutter_wechat_camera_picker#143]
**Version information**
 - Device: iPhone 11
 - OS: IOS 16.0.0
 - Package Version: 3.6.3

**Is your feature request related to a problem?**
When a photo or video is captured, there is a short black flash. I assume the photo / video is loading.
For example, snapchat loads the caputered media instant without black flash.

**Describe the solution you'd like**
A possibility to preload the photo / video before navigating to the "viewer" screen.

**Comment by AlexV525** [comment]
Please verify if the `camera` has the same problem.

**Comment by kareldb** [comment]
I tested it, think it has something to do with the navigator & Flutter's behaviour about handling (large) images/files.

Is there an option to precache the image / file  before calling the method: "pushToViewer" of the class CameraPickerViewer.
This could give the user a smoother experience.

Documentation of precache:
https://api.flutter.dev/flutter/widgets/precacheImage.html

If you don't have the time, I could test & make pull request.

**Comment by AlexV525** [comment]
Sorry that I get your comment wrong, I was thinking about black screens when starting to record videos. Sure a pull request is also welcome.

**Comment by AlexV525** [comment]
Videos are not available for precache in this case.
