### ISSUE TITLE
录制完视频返回的AssetEntity 对象中duration并不是秒

### ISSUE THREAD

**Issue by neusoftliang** [fluttercandies/flutter_wechat_camera_picker#15]
测试录制完视频返回的AssetEntity 对象中duration并不是秒，是需要除以1000吗？

**Comment by AlexV525** [comment]
是秒 返回了多少？

**Comment by AlexV525** [comment]
参考：https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/master/lib/src/widget/builder/audio_page_builder.dart#L80

**Comment by neusoftliang** [comment]
大佬v5,回复真快👍 我这面试着如果是正常10s 的话duration返回的差不多是9900多，除以1000就正好

**Comment by AlexV525** [comment]
cc @CaiJingLong

**Comment by AlexV525** [comment]
如果目前确定不是秒，可以先除。
