### ISSUE TITLE
[BUG] Video recorded in too short duration will be failed to be produced

### ISSUE THREAD

**Issue by hujian-jian** [fluttercandies/flutter_wechat_camera_picker#150]
**Describe the bug**
  I found that when long pressing to record a video, if the user lets go for a short time, it will cause the camera to have a black screen.

**How to reproduce**
No Example

When using the long press to record the video, if you let go in a short time, it will cause the camera to have a black screen
使用长按录屏功能时，用户如果短时间内就松手会导致相机黑屏，我自己是录制几百毫秒松手就必现

**Expected behavior**
I hope that recording the video screen in a short time will not cause the camera to black.

**Screenshots (If contains)**
![1231670380416_ pic](https://user-images.githubusercontent.com/84650087/206073639-693a2a2e-e387-4d9b-99e2-116dcb8fcd41.jpg)

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 2.4.1]
- Flutter Version: [e.g. v2.5.0]

**Additional context**

**Comment by ultronx2** [comment]
I am facing the same issue with android devices.

**Comment by HongZhiQing** [comment]
I am facing the same issue with android devices.

**Comment by HongZhiQing** [comment]
The error log:
I/MediaRecorder(12456): start
I/MediaRecorder(12456): stop
I/CameraDevice-JV-0(12456): Camera now idle
I/Camera  (12456): CameraCaptureSession onClosed
I/CameraDevice-JV-0(12456): Camera now idle
E/MediaRecorder(12456): stop failed: -1007
E/MethodChannel#plugins.flutter.io/camera_android(12456): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera_android(12456): java.lang.RuntimeException: stop failed.
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at android.media.MediaRecorder.native_stop(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at android.media.MediaRecorder.stop(MediaRecorder.java:2179)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at io.flutter.plugins.camera.Camera.stopVideoRecording(Camera.java:761)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:129)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at android.os.Handler.handleCallback(Handler.java:955)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at android.os.Looper.loopOnce(Looper.java:206)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at android.os.Looper.loop(Looper.java:296)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at android.app.ActivityThread.main(ActivityThread.java:9070)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
E/MethodChannel#plugins.flutter.io/camera_android(12456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:968)
[CameraPicker - LOG] Error when stop recording video: CameraException(error, stop failed.)
[CameraPicker - LOG] Try to initialize a new CameraController...
I/flutter (12456): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter (12456): The following CameraException was thrown:
I/flutter (12456): CameraException(error, stop failed.)
I/flutter (12456): 
I/flutter (12456): When the exception was thrown, this was the stack:
I/flutter (12456): #0      handleErrorWithHandler (package:wechat_camera_picker/src/internals/methods.dart:28:3)
I/flutter (12456): #1      CameraPickerState.stopRecordingVideo (package:wechat_camera_picker/src/states/camera_picker_state.dart:749:7)
I/flutter (12456): <asynchronous suspension>
I/flutter (12456): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/Camera  (12456): dispose
I/Camera  (12456): close

**Comment by AlexV525** [comment]
I came up with a solution that might work: I saw many apps add the minimum recording duration limit in the past few months, and most of them are limited to 1 second at least. We might add the same behavior for recordings.
