### ISSUE TITLE
[BUG] CustomCameraPickerState not working in release mode

### ISSUE THREAD

**Issue by WindBise** [fluttercandies/flutter_wechat_camera_picker#159]
**Describe the bug**

I define a CustomCameraPickerState extend CameraPickerState to custom the capture button location,  it works in debug mode, however it's not working in release mode, the capture button and back button disappear.

**How to reproduce**

demo link
https://github.com/WindBise/flutter_wechat_camera_picker/tree/bug_release_button_missing
in example folder

1. cd example folder
2. run debug mode "flutter run --debug"
3. click first button "release版本拍照按钮会消失"
4. then the capture button show on the right side
5. then run command "flutter run --release"
6. click first button "release版本拍照按钮会消失"
7. the capture button disappear

**Expected behavior**

release mode should act same as debug mode

**Screenshots (If contains)**

debug mode screen shoot
![WechatIMG780](https://user-images.githubusercontent.com/34051534/213612617-e62f1c5a-444a-4b78-b235-51806098e154.jpeg)

release mode screen shoot
![WechatIMG779](https://user-images.githubusercontent.com/34051534/213612696-389063b1-1a29-4168-bd69-8c7c15c03f69.jpeg)

**Version information**

- Device: [e.g. iPhone XR]
- OS: [e.g. iOS 15.0.2]
- Package Version: [e.g. 3.6.4]
- Flutter Version: [e.g. v3.0.2 ]

**Additional context**

**Comment by AlexV525** [comment]
The implementation seems invalid during layout which will cause RenderFlex issues. Please update the demo and retry.

**Comment by WindBise** [comment]
Can you tell me how to correct the demo?
