### ISSUE TITLE
Android麦克风权限问题

### ISSUE THREAD

**Issue by siyukok** [fluttercandies/flutter_wechat_camera_picker#16]
你好，情况是这样的，我这边的使用场景只需要拍照，不需要录制视频，但是还是需要获取麦克风权限才能使用CameraPicker，可不可以在不录制视频的情况下，不请求麦克风权限，不然很难跟用户解释

**Comment by AlexV525** [comment]
你好。权限由官方的 camera 进行处理，如果你需要分开权限，请 fork 官方的 camera 并自己修改，而后在依赖冲 override 至自己的版本。

**Comment by siyukok** [comment]
明白了，感谢

**Comment by siyukok** [comment]
#17 看了下camera的源码，可以通过初始化CameraController的时候设置enableAudio参数处理，已提交PR
