### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by jtkeyva** [fluttercandies/flutter_wechat_camera_picker#160]
**Is your feature request related to a problem?**
Support for web

**Describe the solution you'd like**

**Describe alternatives you've considered**
Camera Web Package

**Additional context**
Perhaps if needed, you can dumb things down to make it work on web?. What's holding it back?

**Comment by AlexV525** [comment]
Using the existing methods, the only thing you'll need to do is to update how the captured asset is generated. You can be more specific if you're running into any particular blockings.

**Comment by jtkeyva** [comment]
@AlexV525 i missed your last comment. i'm uncertain how to update thow the asset is generated. you mean to modify the package? web support could be a great addition if it's not too much work. any tips? thx
