### ISSUE TITLE
安卓13上打开黑屏

### ISSUE THREAD

**Issue by cl549723678** [fluttercandies/flutter_wechat_camera_picker#161]
E/flutter ( 5952): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(error, Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference)
E/flutter ( 5952): #0      handleErrorWithHandler (package:wechat_camera_picker/src/internals/methods.dart:28:3)
E/flutter ( 5952): #1      CameraPickerState.initCameras.<anonymous closure> (package:wechat_camera_picker/src/states/camera_picker_state.dart:349:9)

在安卓13上打开黑屏

**Comment by ckq0504** [comment]
pubspec.yaml加入这个试试
camera: ^0.10.3+1
camera_android: ^0.10.4+1
