### ISSUE TITLE
[BUG] goods color not right on vivoIQOO 

### ISSUE THREAD

**Issue by jsshizhan** [fluttercandies/flutter_wechat_camera_picker#172]
**Describe the bug**
goods color not right on vivoIQOO when record video。
（录制视频的时候物品的颜色不对，拍照没问题）

**Expected behavior**
video is real,and not change goods color
(希望录制的视频不要修改物品的颜色)

**Screenshots (If contains)**

![image-2023-05-17-11-32-21-543](https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/8943661/1f14075a-414d-4cb1-8155-ed3753a054fd)
![image-2023-05-17-11-32-21-543](https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/8943661/f12917b7-5f5d-419c-ace1-6b682ad6afbf)

**Version information**

- Device: vivoIQOO 
- OS: android13
- Package Version: 3.8.0
- Flutter Version: 3.0.2

**Additional context**

https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/8943661/8834db62-8bda-4c59-a052-633a66374b05

**Comment by AlexV525** [comment]
Please try with the example of the `camera` package and file issues to the [flutter/flutter](https://github.com/flutter/flutter) if the issue exists.
