### ISSUE TITLE
[BUG] LateInitializationError: Field 'cameras' has already been initialized

### ISSUE THREAD

**Issue by HongZhiQing** [fluttercandies/flutter_wechat_camera_picker#174]
**Describe the bug**
A black screen appears when you press the shoot button on the shooting page.

**How to reproduce**
Using example project

Press and hold the shooting button and release the button immediately when the recording progress bar appears. Huawei mate40 is easy to reproduce.

**Expected behavior**
Prompt that the recording time is less than minimumRecordingDuration

**Screenshots (If contains)**
![21685106216_ pic](https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/37497239/ced843b1-8453-46ec-aede-095b6e282b05)

**Version information**

- Device: Huawei mate 40
- OS: HarmonyOS 3.0.0
- Package Version: 3.8.0
- Flutter Version: v3.7.6

**Additional context**
- error:
"LateInitializationError: Field 'cameras' has already been initialized."

- stack:
"#0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:195:5)
#1      CameraPickerState.cameras= (package:wechat_camera_picker/src/states/camera_picker_state.dart:56:38)
#2      CameraPickerState.initCameras.<anonymous closure> (package:wechat_camera_picker/src/states/camera_picker_state.dart:274:9)
<asynchronous suspension>
"

**Comment by hrxiang** [comment]
The same happened, my log may be more complete
```
/flutter (17026): Error :  LateInitializationError: Field 'cameras' has already been initialized.
I/flutter (17026): StackTrace :  #0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:195:5)
I/flutter (17026): #1      CameraPickerState.cameras= (package:wechat_camera_picker/src/states/camera_picker_state.dart:56:38)
I/flutter (17026): #2      CameraPickerState.initCameras.<anonymous closure> (package:wechat_camera_picker/src/states/camera_picker_state.dart:274:9)
I/flutter (17026): <asynchronous suspension>
D/BufferPoolAccessor2.0(17026): bufferpool2 0xb400007721968428 : 0(0 size) total buffers - 0(0 size) used buffers - 29/34 (recycle/alloc) - 9/29 (fetch/transfer)
D/BufferPoolAccessor2.0(17026): evictor expired: 1, evicted: 1
E/flutter (17026): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (17026): #0      CameraPickerState.controller (package:wechat_camera_picker/src/states/camera_picker_state.dart:51:53)
E/flutter (17026): #1      CameraPickerState.stopRecordingVideo (package:wechat_camera_picker/src/states/camera_picker_state.dart:730:10)
E/flutter (17026): #2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (17026): #3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (17026): #4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (17026): #5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
E/flutter (17026): 
```

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/15884415/c6990043-f0f5-4082-bc5e-e4ea275595b0

I cannot reproduce the issue using the v3.8.0 of the plugin.

**Comment by hrxiang** [comment]
> 20230531_181757.mp4 
> I cannot reproduce the issue using the v3.8.0 of the plugin.

Try stopping before the green progress bar is displayed

**Comment by OnClickListener2048** [comment]
same here
