### ISSUE TITLE
[BUG] 前置摄像头拍照时实时图片和预览时的图片不一致

### ISSUE THREAD

**Issue by eatfishs** [fluttercandies/flutter_wechat_camera_picker#177]
**Describe the bug**

 前置摄像头拍照时实时图片和预览时的图片不一致，预览的图片区域会比实时更大并且图片会反转导致人头歪了
**How to reproduce**

      直接在项目中使用此插件

**Expected behavior**

期望和微信相机一致，实时图片和预览图片保持一致
**Screenshots (If contains)**

**Version information**

wechat_camera_picker: ^3.8.0

**Additional context**

**Comment by std-s** [comment]
@eatfishs Is there any solution?
