### ISSUE TITLE
[BUG] zoom by pulling up when recording video， the screen flicker.

### ISSUE THREAD

**Issue by fifteenjoy** [fluttercandies/flutter_wechat_camera_picker#180]
**Describe the bug**
zoom by pulling up when recording video， the screen flicker. This case only happen on Android device.
**How to reproduce**

https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/5753892/47fc03dd-116d-4e3d-ba4b-a18c6d5d91fe

**Expected behavior**
I hope the screen can be stable

**Version information**

- Device:SamSung galaxy s22
- OS: Android 12
- Package Version: 3.8.0
- Flutter Version: V3.3.10

**Comment by AlexV525** [comment]
Zooming during recording is not triggered by two pointers, you need to pull the held finger up and down and it'll start zooming smoothly.

**Comment by lingyao2333** [comment]
What if I want an additional two-finger trigger, but it doesn't affect it
