### ISSUE TITLE
Compile error with flutter 3.13.0

### ISSUE THREAD

**Issue by huluwa-dev** [fluttercandies/flutter_wechat_camera_picker#186]
**Describe the bug**

Compile error with flutter 3.13.0

**How to reproduce**

Upgrade flutter to the latest stable version 3.13.0, and then use this lib, when compile, you can see the error below.

../../../../../.pub-cache/hosted/pub.dev/wechat_camera_picker-3.8.0/lib/src/widgets/camera_picker.dart:95:9: Error: No named parameter with the name 'primaryVariant'.
    primaryVariant: Colors.grey[900],
    ^^^^^^^^^^^^^^
    ../../../flutter/packages/flutter/lib/src/material/color_scheme.dart:87:9: Context: Found this candidate, but the arguments don't match.
    const ColorScheme({
    ^^^^^^^^^^^

**Version information**

- Device: [e.g. iPhone X]
- OS: [e.g. iOS 14.7.1]
- Package Version:3.8.0
- Flutter Version: 3.13.0

**Comment by AlexV525** [comment]
Use `^v4.0.0-dev.1`.

**Comment by zhoujia456888** [comment]
wechat_camera_picker: ^4.0.0-dev.1  the bug not fix

![image](https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/7905253/0cda9ae2-ace3-47ca-9c90-73f419773301)


> Use `^4.0.0-dev.1`.

**Comment by zhoujia456888** [comment]
> wechat_camera_picker: ^4.0.0-dev.1 the bug not fix
> 
> ![image](https://user-images.githubusercontent.com/7905253/261250217-0cda9ae2-ace3-47ca-9c90-73f419773301.png)
> 
> > Use `^4.0.0-dev.1`.

need Use  wechat_camera_picker: ^4.0.0-dev.3
