### ISSUE TITLE
[BUG] Inverted during video preview

### ISSUE THREAD

**Issue by ehangwork** [fluttercandies/flutter_wechat_camera_picker#188]
**Describe the bug**
When previewing and playing a video, the video is flipped up and down, and other mobile phones test normal。

**How to reproduce**

none!

**Expected behavior**
Display the original video normally。

**Screenshots (If contains)**
[https://sing-duel.oss-cn-shenzhen.aliyuncs.com/1692282102981318.jpg](url)
[https://sing-duel.oss-cn-shenzhen.aliyuncs.com/1692193388910778.mp4](url)

**Version information**

- Device: HUAWEI Mate 40 Pro
- OS: Harmory os 3.0.0
- Package Version: 8.6.3
- Flutter Version: v3.10.6

**Additional context**

**Comment by AlexV525** [comment]
Please verify if using the `video_player` alone has the same issue.
