### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by leonalonso** [fluttercandies/flutter_wechat_camera_picker#19]
First of all, great work!
But you want to know how to change the language. Or add your own text. Thanks

**Comment by AlexV525** [comment]
Do the same thing as assets picker would do, and check the doc.

References: 
* https://github.com/fluttercandies/flutter_wechat_camera_picker#usage-
* https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/master/lib/src/delegates/camera_picker_text_delegate.dart

**Comment by leonalonso** [comment]
Thanks a lot! Sorry I didn't read that right
