### ISSUE TITLE
video record unstable on  realme c17

### ISSUE THREAD

**Issue by heshesh2010** [fluttercandies/flutter_wechat_camera_picker#193]
Hi , I'm using latest version :  4.0.1

and as attached screen recording when I try to capture video it not saved or navigate to preview screen , also it works ok with my Samsung device , but some devices has this issue like realme c17

![WhatsApp Image 2023-08-27 at 5 26 21 PM](https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/16393042/bce85b9b-7be0-4db5-9fac-5cf2727e4ce0)

screen recording : 
https://drive.google.com/file/d/1qwL30ssfAN6rEeMl0Q_P6_OymB7ju9Mr/view?usp=sharing

also I notice that 30s video record will be 75MB , and on Samsung device 30s will be around 16MB . 

code 
```
` await CameraPicker.pickFromCamera(
      context,
      pickerConfig: const CameraPickerConfig(
        maximumRecordingDuration: Duration(minutes: 1),
        shouldAutoPreviewVideo: true,
        enableRecording: true,
        enableTapRecording: true,
        resolutionPreset: ResolutionPreset.medium,
        textDelegate: EnglishCameraPickerTextDelegate(),
      ),
    )`
```

**Comment by AlexV525** [comment]
You'll need to focus on logs or maybe do some Android Native debugging to figure out what goes wrong.

**Comment by heshesh2010** [comment]
> You'll need to focus on logs or maybe do some Android Native debugging to figure out what goes wrong.

this device not main , it some client device , so I can't debug the code

**Comment by AlexV525** [comment]
We just published v4.0.2 which might fixed the issue. You can build from it and see if the situation gets better.

Regarding the file size, it's device-specific which means it's as expected.

Closing, until further useful information has been provided.

**Comment by heshesh2010** [comment]
@AlexV525  I tested again on latest v4.0.2 and still have same results and also I notice camera video recording gets stuck when I try to record about 4 seconds video

**Comment by AlexV525** [comment]
Are versions before 4.0 work fine?

**Comment by heshesh2010** [comment]
I don’t remember so what version u want me to retest ?

**Comment by heshesh2010** [comment]
@AlexV525 I tested on v 3.8.0 and it gives me black screen after record video

**Comment by AlexV525** [comment]
Can you provide some screen recordings? That doesn't seem to related to the plugin itself but the `cemara`.

**Comment by heshesh2010** [comment]
> Can you provide some screen recordings? That doesn't seem to related to the plugin itself but the `cemara`.

@AlexV525 here is https://drive.google.com/file/d/1acAch9Wghw1b8iC3gHSUMQvYqWE37PbZ/view?usp=sharing

**Comment by heshesh2010** [comment]
@AlexV525  any update ?
