### ISSUE TITLE
[BUG] vivo录像卡住了

### ISSUE THREAD

**Issue by Dove900412** [fluttercandies/flutter_wechat_camera_picker#194]
**Describe the bug**
调起相机，长按按钮卡住了（其实是屏幕不动，拍了1张照片），但是进度条正常，几秒之后放开按钮，整个变屏幕白色卡住。

**Version information**
- Device: [e.g. vivo Y93s]
- OS: [e.g. android 8.1.0]
- Package Version: [e.g. last]
- Flutter Version: [e.g. v3.7.10]

**Comment by AlexV525** [comment]
录屏？
