### ISSUE TITLE
[BUG] lockCaptureOrientation not work on IOS real devices

### ISSUE THREAD

**Issue by heshesh2010** [fluttercandies/flutter_wechat_camera_picker#197]
Hi , 
using latest release , when device going to landscape , I found the camera capture button is disappeared when going to landscape , when I return to portrait again the camera button shows again . 

```dart
  await CameraPicker.pickFromCamera(
      context,
      pickerConfig: const CameraPickerConfig(
        
        maximumRecordingDuration: Duration(minutes: 1),
        shouldAutoPreviewVideo: true,
        enableRecording: true,
        lockCaptureOrientation: DeviceOrientation.portraitUp,
        enableTapRecording: true,
        resolutionPreset: ResolutionPreset.medium,
        textDelegate: EnglishCameraPickerTextDelegate(),
      ),
    )
```

**Comment by AlexV525** [comment]
This might be also addressed by #218.

**Comment by heshesh2010** [comment]
@AlexV525 I got many error on iOS 

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: A CameraController was used after being disposed.
Once you have called dispose() on a CameraController, it can no longer be used.
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure>
change_notifier.dart:179
#1      ChangeNotifier.debugAssertNotDisposed
change_notifier.dart:186
#2      ChangeNotifier.notifyListeners
change_notifier.dart:382
#3      ValueNotifier.value=
change_notifier.dart:530
#4      CameraController.lockCaptureOrientation
camera_controller.dart:793
<asynchronous suspension>

**Comment by AlexV525** [comment]
PR updated.

**Comment by heshesh2010** [comment]
@AlexV525  I got too many logs like
[CameraPicker - LOG] X:3.3882041931152345 Y:8.489745483398439 Z:3.4073643493652344

also pls see this screen recording

https://drive.google.com/file/d/1U3OnaexXuCdIWC9utYvgRQi2-WSsMbtS/view?usp=sharing

**Comment by AlexV525** [comment]
Is your device orientation setting locked or unlocked?

**Comment by heshesh2010** [comment]
Unlocked

**Comment by AlexV525** [comment]
> https://drive.google.com/file/d/1U3OnaexXuCdIWC9utYvgRQi2-WSsMbtS/view?usp=sharing

You didn't grant access to this video. :)

**Comment by heshesh2010** [comment]
> > https://drive.google.com/file/d/1U3OnaexXuCdIWC9utYvgRQi2-WSsMbtS/view?usp=sharing
> 
> You didn't grant access to this video. :)

sorry here is 

https://drive.google.com/file/d/1U3OnaexXuCdIWC9utYvgRQi2-WSsMbtS/view?usp=sharing

**Comment by AlexV525** [comment]
> https://drive.google.com/file/d/1U3OnaexXuCdIWC9utYvgRQi2-WSsMbtS/view?usp=sharing

This should be fixed with the updated PR. Please check again.

And please provide a record of your first comment: *I found the camera capture button is disappeared when going to landscape*.

**Comment by heshesh2010** [comment]
@AlexV525 here is new video after pr update

https://drive.google.com/file/d/1WfdsNFRxV0nAK6UOhCJzFMOmGz2NuxPA/view?usp=sharing

the device Orientation lock is off 

and package setting is
           lockCaptureOrientation:
                                  DeviceOrientation.portraitUp,

**Comment by AlexV525** [comment]
Could you try the example of our plugin with your changes instead of a custom implementation and then produce another recording? Thanks for your feedback again.

**Comment by heshesh2010** [comment]
> Could you try the example of our plugin with your changes instead of a custom implementation and then produce another recording? Thanks for your feedback again.

here is with latest pr updated https://drive.google.com/file/d/1dvjBmyC4SEqpmx0ELbhoKqvqQKzisGdX/view?usp=sharing

**Comment by AlexV525** [comment]
PR updated again. After https://github.com/flutter/packages/pull/5261 is published, inverted cases on iOS should be fixed.

**Comment by heshesh2010** [comment]
> PR updated again. After [flutter/packages#5261](https://github.com/flutter/packages/pull/5261) is published, inverted cases on iOS should be fixed.

@AlexV525 ok great work , but why when I use 
lockCaptureOrientation:
DeviceOrientation.portraitUp, 

I didn't notice any change , it should prevent me from landscape mode , but I see it's moving to landsacape, 

also there is error when I stopped the recorder 

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      CameraPickerState.controller (package:wechat_camera_picker/src/states/camera_picker_state.dart:53:53)
#1      CameraPickerState.stopRecordingVideo (package:wechat_camera_picker/src/states/camera_picker_state.dart:979:10)
#2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

**Comment by AlexV525** [comment]
> I didn't notice any change , it should prevent me from landscape mode , but I see it's moving to landscape,

It only locks the capture orientation, not the preview one.

**Comment by Holofox** [comment]
@AlexV525, hi! How to lock preview? The capture button disappears when rotated, and the device's position sensors begin to work in reverse.
