### ISSUE TITLE
[BUG] When recording videos, switch the app to the background and cannot stop recording

### ISSUE THREAD

**Issue by lytian** [fluttercandies/flutter_wechat_camera_picker#205]
**Describe the bug**
Set `enableTapRecording: true`  for CameraPickerConfig. Open the video recording, switch the app to the background, and cannot stop video recording when entering again.

**How to reproduce**
Example can also be reproduced.

1. Set `enableTapRecording: true`  for CameraPickerConfig
2. Open the video recording
3. Switch the app to the background
4. Entering the app again

**Expected behavior**
I hope to stop recording or restart recording.

**Version information**

- Device: OnePlus 7Pro
- OS: Android 11
- Package Version: v4.0.2
- Flutter Version: v3.10.0

**Comment by AlexV525** [comment]
@lytian Could you share a screen recording that reproduces this?

**Comment by AlexV525** [comment]
There indeed some issues about restarting captures, and is fixed by #219.
