### ISSUE TITLE
ios 录制视频出错

### ISSUE THREAD

**Issue by leftcoding** [fluttercandies/flutter_wechat_camera_picker#21]
iphone6s 点击录制视频，出现闪退

 AssetEntity assetEntity = await CameraPicker.pickFromCamera(
      context,
      isAllowRecording: true,
      isOnlyAllowRecording: true,
    );

flutter : Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale zh-Hans-CN

wechat_camera_picker: ^1.3.0

错误代码：Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInputPixelBufferAdaptor appendPixelBuffer:withPresentationTime:] A pixel buffer cannot be appended when readyForMoreMediaData is NO.'

**Comment by AlexV525** [comment]
将 Flutter 升级到今天发布的 `1.22.5` 再尝试一下。

**Comment by leftcoding** [comment]
已解决，可以关闭了。你的插件默认是高分辨，设置地分辨，低版本手机没有问题。
