### ISSUE TITLE
[BUG] 拍照时旋转屏幕，拍照内容也没有旋转

### ISSUE THREAD

**Issue by XutongGithub** [fluttercandies/flutter_wechat_camera_picker#210]
**Describe the bug**
拍照时旋转屏幕，拍照内容也没有旋转

**How to reproduce**
    AssetEntity? asset = await CameraPicker.pickFromCamera(
      context,
      pickerConfig: const CameraPickerConfig(
        enableRecording: true,
        maximumRecordingDuration: Duration(seconds: 120),
        resolutionPreset: ResolutionPreset.veryHigh,
      ),
    );
    if (asset != null) {
      _selectAssetFiles.add(SolicitFile(asset: asset, isCamera: true));
      setState(() {});
    }

打开相机，旋转屏幕

**Expected behavior**
拍照内容也跟着旋转

**Screenshots (If contains)**

**Version information**

- Device: [e.g. iPhone mini]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 4.0.2]
- Flutter Version: [e.g. v3.10.6]

**Additional context**

**Comment by Brislis** [comment]
请问解决了吗

**Comment by XutongGithub** [comment]
邮件已收到。谢谢！

**Comment by luqiuan** [comment]
当iOS系统锁屏按钮关闭，此时拍照预览的时候横屏，预览页会异常，大佬们有遇到吗
