### ISSUE TITLE
[BUG] When I use the camera to take a picture, after I tap the confirm button, it asked me to authorize the photo library, it's ridiculous. I just want to use camera, no need to save it to my photo library.

### ISSUE THREAD

**Issue by Copperfiled** [fluttercandies/flutter_wechat_camera_picker#212]
**Describe the bug**
When I use the camera to take a picture, after I tap the confirm button, it asked me to authorize the photo library, it's ridiculous. I just want to use camera, no need to save it to my photo library.

**How to reproduce**
CameraPicker.pickFromCamera(
        context,
        pickerConfig: CameraPickerConfig()).then((value) {
             print(value);
        })

1. Go to 'pickFromCamera'
2. Click on 'take a picture' 
3. Scroll down to 'confirm' and deny to access the photo library.
4. Got nothing.

**Expected behavior**
After I authorized the Camera,  Even though I denied the photo library, I should take the picture anyway.

**Version information**

- Device: [iPhone X]
- OS: [iOS 17.0]
- Package Version: [4.0.2]
- Flutter Version: [3.13.x]

**Comment by ioschangnan-github** [comment]
iOS如果只给部分相册访问权限时，拍照或拍视频保存时会报错没有权限。

**Comment by AlexV525** [comment]
Use `onEntitySaving` to override the default behavior.
