### ISSUE TITLE
Duplicate onEntitySaving call returned

### ISSUE THREAD

**Issue by sydneyagcaoili** [fluttercandies/flutter_wechat_camera_picker#222]
Bug: When using onEntitySaving, weird behavior happens.

Cause: Duplicate onEntitySaving call when parameter is provided.

The code which fixed the duplicate onEntitySaving was returned after a code change in this PR.

Found a merge issue

_Originally posted by @sydneyagcaoili in https://github.com/fluttercandies/flutter_wechat_camera_picker/pull/216#pullrequestreview-1735591141_

**Comment by AlexV525** [comment]
Thanks for the report.
