### ISSUE TITLE
[BUG] The capture orientation is wrong  in ios 17.0.3 

### ISSUE THREAD

**Issue by cj0x39e** [fluttercandies/flutter_wechat_camera_picker#225]
**Describe the bug**
The CameraPreview will automatically rotate to the wrong orientation when the camera orientation value is ‘landscapeRight’ or ‘landscapeRight’.  It looks like a mirror. And the captured image with the wrong orientation too.

**How to reproduce**
Taking photos with the phone that the IOS version is 17.0.3.

**Expected behavior**
The orientation should be right.

**Version information**

- Device: iPhone 11
- OS: IOS 17.0.3
- Package Version: 4.1.1
- Flutter Version:  3.1.3

**Additional context**

I found a closed issue #224 maybe is the same problem. 

I guess the problem is caused by the accelerometer algorithm, the orientation which got from the accelerometer data may not easy as the source code below. I am not good at this, just an idea.

https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/5fa4614957675ad79aa5d29e17f52a8486abdd11/lib/src/states/camera_picker_state.dart#L496

**Comment by AlexV525** [comment]
Your comment seems include duplicate words like `landscapeRight` which makes me unable determine what you're trying to explain. But I thought it might be something like this: https://github.com/flutter/packages/pull/5261.

If it's the case, run pub upgrade to the latest `camera_avfoundation` to see if it fixes the problem.

**Comment by cj0x39e** [comment]
> Your comment seems include duplicate words like `landscapeRight` which makes me unable determine what you're trying to explain. But I thought it might be something like this: [flutter/packages#5261](https://github.com/flutter/packages/pull/5261).
> 
> If it's the case, run pub upgrade to the latest `camera_avfoundation` to see if it fixes the problem.

It works, thank you so much.
