### ISSUE TITLE
iOS调起相机报错

### ISSUE THREAD

**Issue by ZhongYu5** [fluttercandies/flutter_wechat_camera_picker#226]
VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setAccelerationSamplingPeriod on channel dev.fluttercommunity.plus/sensors/method)
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:313
<asynchronous suspension>
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888

**Comment by theoolee** [comment]
Same here, I'm planning to use another camera lib.

**Comment by hadi7khan** [comment]
I am having same issue when i try to take a video. If i take pictures that is working fine. How did you fix it?
