### ISSUE TITLE
The number of apps taking up storage space on mobile phones has skyrocketed

### ISSUE THREAD

**Issue by wangpeitao123** [fluttercandies/flutter_wechat_camera_picker#229]
Dear developer: Hello! While using the plug-in, I encountered a problem and searched for a long time without finding a solution. Questions as follows: in the use of CameraPicker. PickFromCamera create pictures after the APP takes mobile storage space will continue to increase. If continuous photos are taken, the number of APP storage space occupied by the phone will rise sharply. Plug-in versions: 3.6.3, 4.1.1. Is there any good solution? thank you.

尊敬的开发者： 您好！在使用插件期间，遇到一个问题，查找很久未找到解决方案。问题如下：在使用CameraPicker.pickFromCamera创建拍照后，APP占用手机储存空间会持续增加。如连续拍照，APP占用手机储存空间数值会急剧上升。插件版本：3.6.3，4.1.1。请问有什么好的解决方式吗？谢谢。

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/414b7dc1e447c72d371d30a79e5c2404e0f4ea20/lib/src/constants/config.dart#L89-L93
