### ISSUE TITLE
Interactive improvements

### ISSUE THREAD

**Issue by naamapps** [fluttercandies/flutter_wechat_camera_picker#23]
Thanks for this great package!

I have a few suggestions for you to make this package better:
1. Add the option to zoom (pinch to zoom).
2. Double tap to switch cameras (front to back and vice versa).
3. Add masks to the camera view (square mask or circle mask).

That is all,
Thanks again!

**Comment by AlexV525** [comment]
I think 2 is good, and easy to implement, but I cannot tell whether 1 is supported, and what is 3 for?

**Comment by naamapps** [comment]
Hey @AlexV525,
3 is primarily for UX.
For example, the user needs to shoot a new profile image in a social network (like instagram), the end result of the profile image is going to be circle in the front end, but right now the user doesn't know which part of the image will be taken off because there is no indication in the camera view that the image is circle.
The same with a square image.

Hope you understand,
Thanks!

**Comment by AlexV525** [comment]
A croppable image, right? I didn't use ins a lot, but shouldn't the circle or the mask be provided after the photo has been taken? (For image cropping you can head over to https://github.com/fluttercandies/flutter_image_editor)

**Comment by naamapps** [comment]
@AlexV525,
The package you mentioned is not supporting video unfortunately,
And in my opinion, it is really nice from a user perspective that the image/video you've taken is shown like the end result will be.
I already have a cropping mechanism for images and videos, all I need is a mask just for letting the user know that the image/video will be square/circle.

**Comment by AlexV525** [comment]
Hmm, IMO provide a mask directly is not the best idea, but a customizable builder is reasonable. I'll consider it later.

**Comment by naamapps** [comment]
Great! Looking forward to it 👍

**Comment by libinwalan** [comment]
请问是否可以支持调节曝光度这些参数的设置呢？
目前我使用的是你的微信素材选择器，可以拍照，但是想操作人控制拍照的参数。不知道这个需求难度大不大
谢谢

**Comment by AlexV525** [comment]
Both these features are available on master. See `isAllowPinchToZoom` and `foregroundBuilder`.

**Comment by naamapps** [comment]
Awesome @AlexV525 💯 
I'll take a look ASAP.
I would like to add a suggestion if it's fine by you.
Like Instagram, when recording a video while holding the shutter button, swiping up and down is zooming and unzooming.
Is it possible for you to implement as well?

Also looking forward to the double tap to switch cameras feature.

Thanks for everything!

**Comment by AlexV525** [comment]
This is also under development, there are couple features will be added by recent improvements. Stay tuned.

**Comment by AlexV525** [comment]
> Also looking forward to the double tap to switch cameras feature.

Because no UI relative changes with the feature, it's enabled by default if there are any cameras that can be switched to.

**Comment by naamapps** [comment]
Appreciate it.
For me it's perfect that it's enabled by default.
But maybe worth adding a `doubleTapToSwitchCamerasEnabled` property to give the option to disable it.
Thanks again.

**Comment by AlexV525** [comment]
Variants might be changed due to it's only on master. I'll re-considered if it's worth.

**Comment by naamapps** [comment]
Hey @AlexV525,
Really nice work, I have taken a look and I really like the changes!

A few things worth pointing out:
1. You replaced the switch cameras button at the top with a flash toggle (which is great), but I think you should bring the switch cameras button back and put it next to the shoot button.
2. The exposure control slider is really nice, but there is a bug when the application is in RTL direction. If I swipe up, the slider goes down and if I swipe down the slider goes up.
3. You made the camera preview to fill the whole screen. I don't think it's a good decision because it cuts off the sides of the image to fit the preview into the screen. Only when shooting the photo/video it shows the image with its correct aspect ration. This is a problem because I wanted to put a mask with the `foregroundBuilder`, but it looks super weird because the preview is stretched to fill the screen, so it looks zoomed in.

Hope you will reconsider.
Thank you 👍

**Comment by AlexV525** [comment]
> 3. You made the camera preview to fill the whole screen. I don't think it's a good decision because it cuts off the sides of the image to fit the preview into the screen. Only when shooting the photo/video it shows the image with its correct aspect ration. This is a problem because I wanted to put a mask with the `foregroundBuilder`, but it looks super weird because the preview is stretched to fill the screen, so it looks zoomed in.

That’s how WeChat acts like.

**Comment by AlexV525** [comment]
Currently all your requests are done, as I thought. You can run from master branch again and see if there are more details required to update.

**Comment by naamapps** [comment]
Hi @AlexV525,
Really nice work!
Thank you.

I have an error when confirming the captured photo/video:

```
Unhandled Exception: NoSuchMethodError: The getter 'version' was called on null.
DeviceUtils.isLowerThanAndroidQ (package:wechat_camera_picker/src/utils/device_utils.dart:28)
_CameraPickerViewerState.createAssetEntityAndPop.<anonymous closure> (package:wechat_camera_picker/src/widget/camera_picker_viewer.dart:220)
```

I'm on android 11, Galaxy note20 ultra.

**Comment by AlexV525** [comment]
Try again with the latest commit.

**Comment by naamapps** [comment]
@AlexV525 Yes that fixes the problem!

One last issue I noticed (sorry lol):
If I zoom in the main camera and then switch to the front camera, the zoom delta is not reset, so if I try to zoom in the front camera, the zoom will jump directly to the last zoom value (from the main camera, before the switch).

Thanks again!

**Comment by AlexV525** [comment]
The more you try, the more feedback I got. Thanks for your experience.

**Comment by naamapps** [comment]
Cheers @AlexV525 !
Everything is working flawlessly.
I'm closing this issue.
Thanks for all of this.
Looking forward seeing the changes in a stable release soon.
