### ISSUE TITLE
[BUG] Inappropriate handling when access denied

### ISSUE THREAD

**Issue by Jinxishihenian** [fluttercandies/flutter_wechat_camera_picker#232]
**Describe the bug**

When I currently select an image using this component, the authorization screen pops up and the application crashes when I deny access.
**How to reproduce**

                         // Take pictures and upload them.
                              final AssetEntity? entity =
                                  await CameraPicker.pickFromCamera(
                                context,
                                pickerConfig: const CameraPickerConfig(
                                  enableRecording: false,
                                  onlyEnableRecording: false,
                                ),
                              );

1. Invoke the shooting method.
2. The authorization pop-up window is displayed.
3. Click Reject, and the application crashes.

**Expected behavior**

Disable access to the camera or album, and prompt no permission
**Screenshots (If contains)**

**Version information**

- Device: [nova 5 Pro]
- OS: []
- Package Version: [^8.8.0]
- Flutter Version: [3.16.3]

**Additional context**

     When I refused to grant permission, I didn't print logs
```   
D/RtgSchedIpcFile( 8935): setCommandByIoctl failed ret:-1, cmdid:22, errno:103
E/flutter ( 8935): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(CameraAccessDenied, Camera access permission was denied.)
E/flutter ( 8935): #0      AndroidCamera.createCamera (package:camera_android/src/android_camera.dart:112:7)
E/flutter ( 8935): <asynchronous suspension>
E/flutter ( 8935): fluttercandies/flutter_wechat_assets_picker#1      CameraController._initializeWithDescription (package:camera/src/camera_controller.dart:316:19)
E/flutter ( 8935): <asynchronous suspension>
E/flutter ( 8935): fluttercandies/flutter_wechat_assets_picker#2      CameraPickerState.initCameras.<anonymous closure> (package:wechat_camera_picker/src/states/camera_picker_state.dart:395:9)
E/flutter ( 8935): <asynchronous suspension>
E/flutter ( 8935):

**Comment by Jinxishihenian** [comment]
I appreciate your attention to this issue

**Comment by Jinxishihenian** [comment]
Currently using plugins to judge permissions in advance, this can make me work well
```
PermissionStatus status =  await Permission.camera.request();
if (status.isGranted) {
}else{
}

**Comment by Jinxishihenian** [comment]
![image](https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/44466363/1ffcce7d-df31-48b0-bdf5-d6114c0a2d50)
I have something to do with the library you rely on
https://pub.dev/packages/camera

**Comment by AlexV525** [comment]
I confirmed that the issue is caused by the recursive calls. Fixing.
