### ISSUE TITLE
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888

### ISSUE THREAD

**Issue by hadi7khan** [fluttercandies/flutter_wechat_camera_picker#233]
I am trying to take pictures n videos in my app using this package. It works fine at first, but when I try to click more picture n videos then app is crashing with error: 

"[CameraPicker - LOG] 0:00:00.237877 for controller's initialization.
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
Lost connection to device.".

this is my code: 
    Future<void> _pickMedia(context) async {
    var pickedFile;
    await CameraPicker.pickFromCamera(context,
        pickerConfig: CameraPickerConfig(
          enableRecording: true,
          textDelegate: EnglishCameraPickerTextDelegate(),
          onEntitySaving: (context, viewType, file) {
            pickedFile = file;
          },
          onXFileCaptured: (p0, p1) {
            pickedFile = p0;
            Navigator.of(context).pop();
            return true;
          },
        ));
    if (pickedFile != null) {
      try {
        final XFile? file = await pickedFile;

        if (file != null) {
          String filePath = file.path;
          log('File path: $filePath');
          setState(() {
            _image = XFile(filePath);
          });
        } else {
          print('Error: Unable to load file.');
        }
      } catch (e) {
        print('Error: $e');
      }
    }
  }

It works fine at first but If i try to take videos n pictures again n again then app gets crashed

**Comment by hadi7khan** [comment]
@AlexV525 Why did you close it? I have added clear question n description as well. Shared the code snippet also

**Comment by AlexV525** [comment]
Read #31

**Comment by hadi7khan** [comment]
ok, you want me to create new issue with full code and description? Because using this package is crashing my app

**Comment by zhoudajun-ola** [comment]
> ok, you want me to create new issue with full code and description? Because using this package is crashing my app

see my reply: https://github.com/fluttercandies/flutter_wechat_camera_picker/issues/162
