### ISSUE TITLE
create fail, error: Error Domain=PHPhotosErrorDomain Code=3302 "(null)"

### ISSUE THREAD

**Issue by chuxideyanhuo** [fluttercandies/flutter_wechat_camera_picker#238]
调用相机录制视频，点击确认，提示保存后报Error Domain=PHPhotosErrorDomain Code=3302，代码如下：

final AssetEntity? aEntity = await CameraPicker.pickFromCamera(
      context,
      pickerConfig: CameraPickerConfig(
        enableRecording: true,
        onlyEnableRecording: true,
        maximumRecordingDuration: Duration(
          seconds: 15,
        ),
      ),
    );

**Version information**
- Device: [Mac M1]
- OS: [MacOS 14.4 (23E214)]
- Package Version: [4.2.0]
- Flutter Version: [V3.16.7]

**Comment by AlexV525** [comment]
机型？

**Comment by jianxingbieli** [comment]
> 机型？

目前 6Plus,7Plus,X都复现了 ，别的手机没尝试，应该都会复现这个错误
`        final AssetEntity? entity = await CameraPicker.pickFromCamera(
          RouterHelper.getCurrentContext(),
          pickerConfig: const CameraPickerConfig(enableRecording: true),
        );`
最新版4.2.1是同样的错误

**Comment by jianxingbieli** [comment]
> > 机型？
> 
> 目前 6Plus,7Plus,X都复现了 ，别的手机没尝试，应该都会复现这个错误 ` final AssetEntity? entity = await CameraPicker.pickFromCamera( RouterHelper.getCurrentContext(), pickerConfig: const CameraPickerConfig(enableRecording: true), );` 最新版4.2.1是同样的错误

经测试，必须添加onEntitySaving的回调，才能拿到ios的录像数据

**Comment by Huangfuzhimin** [comment]
我也遇到了这个问题，在Android上表现良好，在iOS遇到此问题，同时导致卡顿、一定概率闪退，拿不到首帧，最终用resolutionPreset: ResolutionPreset.high处理得到了最好的效果

这个参数默认是this.resolutionPreset = ResolutionPreset.max,
会用最高分辨率，闪退后查得 https://github.com/flutter/flutter/issues/69874
根据标题的高分辨率来推测，修改分辨率后得到有效解决

**Comment by AlexV525** [comment]
请把问题开给 flutter 的 camera
