### ISSUE TITLE
[Feature] AspectRatio/Resolution control

### ISSUE THREAD

**Issue by blok5025** [fluttercandies/flutter_wechat_camera_picker#242]
**Is your feature request related to a problem?**
Right now, all of the videos are recorded in a 16:9/9:16 ratio.

**Describe the solution you'd like**
I would like to be able to pass a custom ratio such as 4:5, 4:3, or 1:1

**Describe alternatives you've considered**
Other than modifying the previewer using `AspectRatio()` there is nothing to do. No controller other than the video quality is offered.

**Additional context**
N/A

**Comment by AlexV525** [comment]
This is not supported by the underlying `camera` package.
