### ISSUE TITLE
[Feature] CameraController的value里面返回录制时长

### ISSUE THREAD

**Issue by lytian** [fluttercandies/flutter_wechat_camera_picker#247]
**Version information**
 - Device: *e.g. iPhone X*
 - OS: *e.g. iOS 14.7.1*
 - Package Version: *e.g. v3.0.0.*
 - Flutter Version: *e.g. v3.16.0*

**Describe the solution you'd like**

CameraController的value里面返回录制时长

**Comment by AlexV525** [comment]
CameraValue 不由 package 控制，请把请求开给 camera。
