### ISSUE TITLE
[Feature] camera依赖升级到^0.11.0

### ISSUE THREAD

**Issue by lytian** [fluttercandies/flutter_wechat_camera_picker#248]
**Version information**
 - Device: *e.g. iPhone X*
 - OS: *e.g. iOS 14.7.1*
 - Package Version: *e.g. v2.4.1*
 - Flutter Version: *e.g. v2.5.0*

**Is your feature request related to a problem?**
和本地项目的camera依赖冲突

**Describe the solution you'd like**
camera依赖升级到^0.11.0

**Comment by AlexV525** [comment]
目前没法更换，具体实现问题还非常多。

**Comment by lytian** [comment]
期待有更好的解决方案
