### ISSUE TITLE
Camera tuning improvements

### ISSUE THREAD

**Issue by libinwalan** [fluttercandies/flutter_wechat_camera_picker#25]
请问是否可以支持调节曝光度这些参数的设置呢？
目前我使用的是你的微信素材选择器，可以拍照，但是想操作人控制拍照的参数。不知道这个需求难度大不大
谢谢

**Comment by AlexV525** [comment]
已经在根据 0.6.x 的 camera 开发。

**Comment by AlexV525** [comment]
Closed in 2.0.0-dev.1 .
