### ISSUE TITLE
[BUG] enableRecording true cause ios crash when open the camera

### ISSUE THREAD

**Issue by cmlanche** [fluttercandies/flutter_wechat_camera_picker#251]
**Describe the bug**
when set enableRecording true, on the ios device , open camera crash right now.
if set enableRecording false, then it is ok

**How to reproduce**
```
CameraPicker.pickFromCamera(c,
      pickerConfig: const CameraPickerConfig(enableRecording: true),
    );
```
call the code

just click start take camera button, then crash , hanppen with sure

**Expected behavior**
dont crash

**Screenshots (If contains)**

https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/5886757/205e2588-ed3d-4996-ab8b-59834e723d03

**Version information**

- Device: iphone 11
- OS: 16.3
- Package Version: 4.2.2
- Flutter Version: 3.22.0

**Additional context**

**Comment by AlexV525** [comment]
This is not reproducible with the example of the plugin. Refer to the README to resolve the problem.
