### ISSUE TITLE
[BUG]拍照/拍视频完成进入预览页面，照片或者视频是逆时针旋转90度的。

### ISSUE THREAD

**Issue by tfn290181662** [fluttercandies/flutter_wechat_camera_picker#253]
**Describe the bug**
拍照/拍视频完成进入预览页面，照片或者视频是逆时针旋转90度的。

从手机文件管理器中打开拍摄的照片和视频，都是被旋转90度的。

**How to reproduce**

```
 final AssetEntity? entity = await CameraPicker.pickFromCamera( context,
       pickerConfig: CameraPickerConfig(
           enableRecording: true
       ),
	）;
```

见下方的截图

**Expected behavior**
拍摄的图片和视频不应该被旋转

**Screenshots (If contains)**
![Screenshot_2024-06-20-09-30-50-387_com eleadin gd ssyh](https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/92365265/90bd5477-34ca-4b6a-9f34-3b9b328ec8fa)
![Screenshot_2024-06-20-09-31-15-560_com eleadin gd ssyh](https://github.com/fluttercandies/flutter_wechat_camera_picker/assets/92365265/b6ad05f8-57a8-4975-beb6-a71a069ec5e6)

**Version information**

- Device: Redmi Note13 / iPhone14ProMax(两个机型都试过，都有此问题)
- OS: Android13 / iOS 16.4
- Package Version: v4.2.2
- Flutter Version: 3.22.2

**Additional context**
无

**Comment by tfn290181662** [comment]
视频和照片都是如此

**Comment by AlexV525** [comment]
通过 example 尝试并完整录屏。

**Comment by tfn290181662** [comment]
是我的问题，参数传错了

**Comment by yuanliangYL** [comment]
> 是我的问题，参数传错了

我也有这个问题，请问是需要设置哪个参数吗？
