### ISSUE TITLE
[Feature] Request a feature with something

### ISSUE THREAD

**Issue by changewhite** [fluttercandies/flutter_wechat_camera_picker#256]
**Version information**
 - Device: *Samsung  SM911U*
 - OS: *e.g. iOS 14.7.1*
 - Package Version: *e.g. v4.3.0*
 - Flutter Version: *e.g. v3.19.6*

**Is your feature request related to a problem?**
1.How to cancel the black background at the bottom of the camera, for example: set it to transparent

**Describe the solution you'd like**
Add color settings at the bottom of the camera interface

**Describe alternatives you've considered**
Can you add buttons for selecting images and videos on the camera interface

**Additional context**
No

**Comment by AlexV525** [comment]
1. Walk through the example.
2. https://github.com/fluttercandies/flutter_wechat_camera_picker?tab=readme-ov-file#using-custom-states
