### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by changewhite** [fluttercandies/flutter_wechat_camera_picker#259]
**Describe the bug**
Using SM-S911U to download the demo and take photos or videos, clicking on the switch between front and rear cameras on the shooting interface will cause the shooting button to shake up and down

**How to reproduce**

4. Error occurred.

**Expected behavior**
Fix this bug

**Screenshots (If contains)**

**Version information**

- Device: [e.g. SM-S911U]
- OS: [e.g. iOS 14.7.1]
- Package Version: [e.g. 4.3.0+1]
- Flutter Version: [e.g. v3.19.6]

**Additional context**

**Comment by AlexV525** [comment]
This will happen because cameras return different aspect ratios and the section will calculate accordingly. There is no way we can configured the aspect ratio since the `package:camera` does not provide that ability.

**Comment by changewhite** [comment]
But I didn't have this issue when using version 4.2.2, and I am also using the same phone

**Comment by AlexV525** [comment]
You can flip the `enableScaledPreview` to see if it helps

**Comment by changewhite** [comment]
52/10000
实时翻译
52/10000尝试启用ScaledPreview仍然没有成功，主要是因为4.2.2版本没有问题，但它在更新后出现了

划译
Trying to enableScaledPreview still didn't work, mainly because there was no problem with version 4.2.2, but it appeared after the update

**Comment by changewhite** [comment]
Trying to enableScaledPreview still didn't work, mainly because there was no problem with version 4.2.2, but it appeared after the update

**Comment by AlexV525** [comment]
Should be fixed in https://github.com/fluttercandies/flutter_wechat_camera_picker/pull/258.
