### ISSUE TITLE
建议修改成区间版本

### ISSUE THREAD

**Issue by DizzyYang** [fluttercandies/flutter_wechat_camera_picker#26]
photo_manager: ">=0.5.8 <2.0.0"

**Comment by AlexV525** [comment]
原因？

**Comment by DizzyYang** [comment]
因为部分插件都有使用 photo_manager 都在指定不同的版本 所以很容易造成冲突

wechat_assets_picker 设置了区间版本

而且photo_manager也会有bug产生 photo_manager也会在不更改api情况下修复了bug

**Comment by AlexV525** [comment]
camera picker 和 photo_manager 近期计划有很多改动，根据 @CaiJingLong 的反馈暂不进行调整，待发布后处理。

**Comment by AlexV525** [comment]
冲突请自行 override
