### ISSUE TITLE
[BUG] Black preview after 4.2.1 version

### ISSUE THREAD

**Issue by shpy2001** [fluttercandies/flutter_wechat_camera_picker#267]
**Describe the bug**
Get black screen preview. But hit capture button, it can capture image and save to device.
This happened when switching from version 4.2.1 to 4.3.1. Just roll back to version 4.2.1 and everything will be back to normal.

Device tested: 
- Oppo A70 Android 11.
- Samsung A54 Android 14.
- 
![z5712791203973_d97913769b4a9e74df72039e0aed6ebf](https://github.com/user-attachments/assets/d81dd0d3-0251-4cc8-b24b-cd749907b1f8)

**Comment by AlexV525** [comment]
Please attach a screen recording using the example of the plugin.
