### ISSUE TITLE
Preview screen scale error

### ISSUE THREAD

**Issue by changewhite** [fluttercandies/flutter_wechat_camera_picker#275]
**Describe the bug**
After shooting the video, the preview screen changes to portrait mode

**How to reproduce**
pickerConfig:CameraPickerConfig(
                    enableRecording: true,
)

4. Error occurred.

**Expected behavior**
Obtain the correct image

**Screenshots (If contains)**

**Version information**

- Device: SM-S911U/DS
- OS: android 14
- Package Version: 4.3.2
- Flutter Version: 3.24.2

**Additional context**
Photo_manager used: ^ 3.5.0

**Comment by changewhite** [comment]
On September 5th, someone mentioned this issue, and your answer was that photo_manager: ^ 3.3.0 has been fixed. However, using photo_manager: ^ 3.5.0 still causes this problem, and using the example also causes it

**Comment by AlexV525** [comment]
Where did I mention this? Also please attach screenshot

**Comment by changewhite** [comment]
![Uploading 364652694-49007043-04b0-4bd3-b419-900cd5392fb2.jpeg…]()

**Comment by changewhite** [comment]
<img width="634" alt="1728445179280" src="https://github.com/user-attachments/assets/8a008197-0ef6-472b-90dc-d414b2e04a70">
<img width="634" alt="1728445179280" src="https://github.com/user-attachments/assets/8a008197-0ef6-472b-90dc-d414b2e04a70">

**Comment by changewhite** [comment]
![364652694-49007043-04b0-4bd3-b419-900cd5392fb2](https://github.com/user-attachments/assets/d3238b99-a19e-41eb-aa9b-102389921417)

**Comment by AlexV525** [comment]
See https://github.com/flutter/flutter/issues/154696

**Comment by changewhite** [comment]
Okay I go take  look
