### ISSUE TITLE
[BUG] 只需要用到拍照，Android 13 时候会检查到video 和audio的权限

### ISSUE THREAD

**Issue by chenxin0916** [fluttercandies/flutter_wechat_camera_picker#277]
拍照点击确定按钮后，在做权限检查的时候用了默认构造创建了RequestType.common类型的权限检查
<img width="997" alt="Screenshot 2024-10-14 at 16 23 51" src="https://github.com/user-attachments/assets/5f4abab1-cf66-4587-b6ba-aba5444206b9">

在Photo_manager库中RequestType.common 在对印`PermissionDelegate33` 检查了`Manifest.permission.READ_MEDIA_VIDEO`, `Manifest.permission.READ_MEDIA_AUDIO`, `Manifest.permission.READ_MEDIA_IMAGES` 但是前面两个没用到，能否灵活设置了？

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_camera_picker/commit/24683d1bd28d8b9d9cc8ae003c10c0407c3942f7
