### ISSUE TITLE
Video is saving but unable to play

### ISSUE THREAD

**Issue by EjazAmir** [fluttercandies/flutter_wechat_camera_picker#28]
Hi, im recording video using this, and the video also saved to the gallery but unable to play the video from gallery. kindly anyone faced this issue so please help.

**Comment by AlexV525** [comment]
Usage code, device models, relative logs.

**Comment by EjazAmir** [comment]
no device logs, as it saves the video to gallery. Device model is huawei y9 2019 android 9.1. Using the same example code
![WhatsApp Image 2021-01-13 at 1 58 12 PM](https://user-images.githubusercontent.com/25684301/104429438-6eb22480-55a7-11eb-82c6-797cb3ba94a2.jpeg)

**Comment by AlexV525** [comment]
Can you try with `2.0.0-dev.2` or master branch to see if it's reproducible?
