### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by huangkunhe** [fluttercandies/flutter_wechat_camera_picker#287]
**Describe the bug**
ipad 打开相机黑屏，无法拍照。

**How to reproduce**
打开相机拍照

打开相机拍照

**Expected behavior**

**Screenshots (If contains)**
flutter: 错误信息1：Null check operator used on a null value
flutter: 错误信息2：#0      CameraPickerState.wrapControllerMethod (package:wechat_camera_picker/src/states/camera_picker_state.dart:316:22)
flutter: #1      CameraPickerState.initCameras.<anonymous closure> (package:wechat_camera_picker/src/states/camera_picker_state.dart:479:15)
flutter: <asynchronous suspension>

**Version information**

- Device: ipad
- OS: iOS14.0
- Package Version: 4.2.0
- Flutter Version: 3.19

**Additional context**

**Comment by AlexV525** [comment]
使用最新版本。

**Comment by AlexV525** [comment]
看文档，不负责解决先前的版本的错误。
