### ISSUE TITLE
你好 能否支持修改拍摄按钮 和拍摄中视频进度回调 

### ISSUE THREAD

**Issue by Slhaos7373** [fluttercandies/flutter_wechat_camera_picker#289]
你好 能否支持修改拍摄按钮 和拍摄中视频进度回调 这些都需要自定义 我用了一年多了 一直在找这个文档 没有找到 有时候需要在相机页面 做一个相册选取的功能 现在很多视频拍摄都带这个功能

**Comment by Slhaos7373** [comment]
这是我的qq号 717817373 需要您的支持

**Comment by Slhaos7373** [comment]
![Uploading 9cad588aaa0320e2183be9dc6ceb372b.png…]()
****

**Comment by Slhaos7373** [comment]
![Uploading 9cad588aaa0320e2183be9dc6ceb372b.png…]()

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/main/README-ZH.md#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-state
