### ISSUE TITLE
长按拍摄的进度条颜色，跟随主题颜色可否增加一下

### ISSUE THREAD

**Issue by barretzhi** [fluttercandies/flutter_wechat_camera_picker#34]
![image](https://user-images.githubusercontent.com/10612276/115174949-c27b5f00-a0fc-11eb-9beb-ef2c1bcec5ed.png)
精度条组件颜色设置参数有，但是picker内未设置

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/master/lib/src/widget/camera_picker.dart#L138
