### ISSUE TITLE
使用过程中的几点建议

### ISSUE THREAD

**Issue by aiqianxian** [fluttercandies/flutter_wechat_camera_picker#37]
1. 有没有选项调节默认前置摄像头
2. 有没有选项默认关闭闪光灯
3. 有没有选项默认写入私有文件夹中，不然iOS会弹个访问照片的提示框

**Comment by AlexV525** [comment]
> 1. 有没有选项调节默认前置摄像头

没有，因为根据实际情况来看，有些设备的可用摄像头数量会超过2，且索引为1的摄像头不一定是前置。

> 2. 有没有选项默认关闭闪光灯

可以考虑增加。

> 3. 有没有选项默认写入私有文件夹中，不然iOS会弹个访问照片的提示框

需求是？

另外，请根据 issue template 重新开 issue。ref #31 .
