### ISSUE TITLE
[Bug] Can't handle exceptions

### ISSUE THREAD

**Issue by Holofox** [fluttercandies/flutter_wechat_camera_picker#41]
The package suppresses all exceptions that may occur while working with the camera. This is not correct because it is not possible to handle the denial of permission to access the camera and any other exception that is thrown.

Take a look at the following pieces of code:

https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/82125328f95155673688cb0c7890defece0b09e3/lib/src/widget/camera_picker.dart#L537-L539

https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/82125328f95155673688cb0c7890defece0b09e3/lib/src/widget/camera_picker.dart#L575-L577

I gave as an example, in fact, there are more such places.

**Comment by AlexV525** [comment]
Thanks for the feedback. If you're able to submit a PR for this, I'll be happy to help you land an enhancement, since I'm quite busy in some other works.
