### ISSUE TITLE
wechat_camera_picker所依赖的camera插件，未使用就获取了mac地址信息这块有什么处理办法吗？

### ISSUE THREAD

**Issue by Etermally** [fluttercandies/flutter_wechat_camera_picker#45]
When testing the Android privacy compliance protocol, it was found that the wechat_camera_picker plugin library obtained the mac address information without calling any permissions. Is there any solution here? Blogger thank you
由于测试安卓隐私合规协议时，在未调用任何权限时，就发现wechat_camera_picker插件库获取了mac地址信息，这里有什么解决办法吗？博主，非常感谢

**Comment by AlexV525** [comment]
#31 . Please file issues targeting the `camera` plugin.
