### ISSUE TITLE
Record video without the user to keep holding record button

### ISSUE THREAD

**Issue by lighttt** [fluttercandies/flutter_wechat_camera_picker#46]
Hello, I really liked the package, and the resolution preset it has given is really an awesome feature. Thank you! 
However, I used the params for `onlyEnableRecording: true` and I wanted the user to just tap the record button to start recording instead of the need to hold it. Is there any way this is possible? Also, I would really appreciate it if there was a Timer showing the recorded time.

**Comment by AlexV525** [comment]
We need a more common pattern, instead of a "similar to some app"'s solution. More precisely, we need at least a public param for this to control the timer and the record behavior separately.

**Comment by ZhuBoao** [comment]
I believe this is an actually very reasonable feature request. Once we set onlyEnableRecording to true, it's kind of silly to force the users to long press the recording button while the tap behaviour are none-functional.
