### ISSUE TITLE
Camera crash problem

### ISSUE THREAD

**Issue by goodswifter** [fluttercandies/flutter_wechat_camera_picker#47]
Hi, this package is **great**. Thank you
I have a problem now, when users are not allowed to use the album, it will crash when the photo is taken. I think users can also get AssetEntity when they are not allowed to use the album. I hope you can solve this problem, thank you

**Comment by AlexV525** [comment]
It's a dangerous behavior to put things like these (photos, videos) into the memory, since you won't know when your app will be terminated due to the memory usage.

Regarding the crash, I'll take some time to investigate in avoid crash the app.

**Comment by goodswifter** [comment]
OK...Thanks
