### ISSUE TITLE
运行demo 后置摄像头拍照报错

### ISSUE THREAD

**Issue by lailiaomm** [fluttercandies/flutter_wechat_camera_picker#48]
后置摄像头拍照报错
手机：小米 redmi 10x
log：
E/flutter (13213): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: CameraException(captureTimeout, Picture capture request timed out)
E/flutter (13213): #0      CameraController.takePicture (package:camera/src/camera_controller.dart:346:7)
E/flutter (13213): <asynchronous suspension>
E/flutter (13213): #1      CameraPickerState.takePicture (package:wechat_camera_picker/src/widget/camera_picker.dart:738:23)
E/flutter (13213): <asynchronous suspension>

前置摄像头拍照没有问题

**Comment by AlexV525** [comment]
试一下官方的 camera 是否有同样的情况，如果有的话，在 flutter repo 提一个 issue。

**Comment by lailiaomm** [comment]
最新版的camera解决了这个问题 作者更新下吧 谢谢
