### ISSUE TITLE
MissingPluginException(No implementation found for method requestPermission on channel top.kikt/photo_manager

### ISSUE THREAD

**Issue by ITmxs** [fluttercandies/flutter_wechat_camera_picker#51]
wechat_assets_picker:
    dependency: "direct main"
    description:
      name: wechat_assets_picker
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "4.2.2"

flutter：1.22.6
androidx

**Comment by AlexV525** [comment]
#31
