### ISSUE TITLE
[BUG] Recording video cause freeze in a moment and the first couple frames are black

### ISSUE THREAD

**Issue by hrxiang** [fluttercandies/flutter_wechat_camera_picker#55]
### **The ios recording video has a freeze when you first press and hold the video, and the screen is black after the video is recorded**

device: iphone 6sp/11 etc.
os:        14.8
wechat_camera_picker: ^2.5.0
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (8 weeks ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

**Comment by AlexV525** [comment]
Any screen records?

**Comment by hrxiang** [comment]
https://user-images.githubusercontent.com/7018230/140256714-d760b457-6d19-4ef2-9333-c74c3b55d351.mp4

**Comment by AlexV525** [comment]
Is the video has a black screen at the very first frames, or it's completely black?

**Comment by hrxiang** [comment]
It should be that the recording failed. After clicking OK to build, nothing was obtained.

**Comment by AlexV525** [comment]
Can you try with the example of the `camera` plugin and see if the video can be recorded when this method is called first?
https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/3b38cbe23a7cef46ae1dcd556780a7906124b352/lib/src/widgets/camera_picker.dart#L782

**Comment by AlexV525** [comment]
Separating this into two separate issues.

**Comment by AlexV525** [comment]
Found related issues:
- https://github.com/flutter/flutter/issues/90600
- https://github.com/flutter/flutter/issues/57831

We can make fewer black frames, but the first frame is by the `camera` plugin itself, which is the issue we can't fix at the moment.
