### ISSUE TITLE
[BUG]  Android5.0系统vivo X5M和Android7.0系统华为TRT-AL00A拍照黑屏、点击无反应

### ISSUE THREAD

**Issue by JL521** [fluttercandies/flutter_wechat_camera_picker#56]
Android5.0系统vivo X5M拉起相机界面黑屏、点击拍照 没有反应
Android7.0系统华为TRT-AL00A正常拉起相机，点击拍照成功后没有反应

**Comment by JL521** [comment]
打印信息：

I/Camera  (32745): startPreview

E/CameraDevice-0-LE(32745): Surface with size (w=1920, h=1080) and format 0x21 is not valid, size not in valid set: [4160x3120, 4096x2160, 3264x2448, 3200x2400, 3328x1872, 2560x1920, 2560x1440, 2048x1536, 1600x1200, 1280x960, 1280x768, 1280x720, 1024x768, 800x480, 720x480, 640x480, 320x240]

W/CameraDevice-JV-0(32745): Stream configuration failed

E/CameraCaptureSession(32745): Session 0: Failed to create capture session; configuration failed

I/Camera  (32745): runPrecaptureSequence

E/MethodChannel#plugins.flutter.io/camera(32745): Failed to handle method call

E/MethodChannel#plugins.flutter.io/camera(32745): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference

E/MethodChannel#plugins.flutter.io/camera(32745):  at io.flutter.plugins.camera.Camera.runPrecaptureSequence(Camera.java:489)

E/MethodChannel#plugins.flutter.io/camera(32745):  at io.flutter.plugins.camera.Camera.takePicture(Camera.java:474)

E/MethodChannel#plugins.flutter.io/camera(32745):  at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:114)

E/MethodChannel#plugins.flutter.io/camera(32745):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)

E/MethodChannel#plugins.flutter.io/camera(32745):  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)

E/MethodChannel#plugins.flutter.io/camera(32745):  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)

E/MethodChannel#plugins.flutter.io/camera(32745):  at android.os.MessageQueue.nativePollOnce(Native Method)

E/MethodChannel#plugins.flutter.io/camera(32745):  at android.os.MessageQueue.next(MessageQueue.java:143)

E/MethodChannel#plugins.flutter.io/camera(32745):  at android.os.Looper.loop(Looper.java:122)

E/MethodChannel#plugins.flutter.io/camera(32745):  at android.app.ActivityThread.main(ActivityThread.java:5305)

E/MethodChannel#plugins.flutter.io/camera(32745):  at java.lang.reflect.Method.invoke(Native Method)

E/MethodChannel#plugins.flutter.io/camera(32745):  at java.lang.reflect.Method.invoke(Method.java:372)

E/MethodChannel#plugins.flutter.io/camera(32745):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)

E/MethodChannel#plugins.flutter.io/camera(32745):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

[CameraPicker - LOG] "Error when preview the captured file: CameraException(error, Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference)"

**Comment by AlexV525** [comment]
尝试官方的 camera 有没有问题。

**Comment by JL521** [comment]
试了、官方的 camera 没有问题

**Comment by AlexV525** [comment]
执行 `flutter pub upgrade`，确认 `pubspec.lock` 内 `camera` 版本与 官方最新一致后，再次尝试。如有问题请录屏，且提供调用栈。
