### ISSUE TITLE
Confirm button text is hard coded

### ISSUE THREAD

**Issue by mordeccai** [fluttercandies/flutter_wechat_camera_picker#6]
The confirm button text for this plugin has been hardcoded and can not be changed to English. The value set in the getter `previewConfirmButton` is 完成

**Comment by AlexV525** [comment]
Thanks for find it out! I'll fix it tomorrow.

**Comment by AlexV525** [comment]
For the record:
https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/4d7f9ff8f7c3afdce1045f0427ee01fb099a8f41/lib/src/widget/camera_picker_viewer.dart#L279-L280
