### ISSUE TITLE
Failed to find GeneratedAppGlideModule

### ISSUE THREAD

**Issue by hrxiang** [fluttercandies/flutter_wechat_camera_picker#60]
W/Glide   (23337): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
D/skia    (23337): --- Failed to create image decoder with message 'unimplemented'
D/skia    (23337): --- Failed to create image decoder with message 'unimplemented'

wechat_camera_picker: ^2.6.0

**Comment by AlexV525** [comment]
你们到底会不会看文档？https://github.com/fluttercandies/flutter_wechat_camera_picker/blob/master/README-ZH.md#%E9%85%8D%E7%BD%AE
