### ISSUE TITLE
[BUG] shouldDeletePreviewFile 设置为true后 拍照保存  图库里并没有删除掉  还会有拍照的那张照片

### ISSUE THREAD

**Issue by purgeyao** [fluttercandies/flutter_wechat_camera_picker#63]
shouldDeletePreviewFile 设置为true后 拍照保存  图库里并没有删除掉  还会有拍照的那张照片

**Comment by AlexV525** [comment]
#31

**Comment by SyedAshiqSorife** [comment]
@purgeyao did you find any solution of this problem??

**Comment by AlexV525** [comment]
`shouldDeletePreviewFile` represents the `XFile` captured by the `camera` plugin, not the `AssetEntity` saved by `photo_manager` which must be inserted into the `MediaStore`. If you don't want to obtain the `AssetEntity`, implement `onEntitySaving`.

**Comment by SyedAshiqSorife** [comment]
Thank you @AlexV525  for your response.... i want to to picked a image by camera using wechat_camera_pickerand want to upload it to database but not want to save in my phone gallery....so can you please so example that how to not save it on gallery by implementing onEntitySaving??

**Comment by SyedAshiqSorife** [comment]
cause i don't understand how to implement onEntitySaving

**Comment by AlexV525** [comment]
See [the document](https://pub.dev/documentation/wechat_camera_picker/latest/wechat_camera_picker/EntitySaveCallback.html) of the callback.

**Comment by Nasar-uddin** [comment]
> See [the document](https://pub.dev/documentation/wechat_camera_picker/latest/wechat_camera_picker/EntitySaveCallback.html) of the callback.

This documentation doesn't clear anything. Could you please post an example.
I wanted to capture image and return the file as return. But using on onEntitySaving I couldn't solve that. Here is my function- 
`static Future<File> getImageByCamera(BuildContext context) async {
    try{
      final AssetEntity result = await CameraPicker.pickFromCamera(
        context,
        pickerConfig: CameraPickerConfig(
          // shouldDeletePreviewFile: true,
          enableRecording: false,
          textDelegate: EnglishCameraPickerTextDelegate(),
          onEntitySaving: (ctx, pickerType, File file){
            print(file.path);
            return file;
          }
        ),
      );
      if(result != null){
        File pickedFile = await result.file;
        pickedFile = await compressFile(pickedFile);
        return pickedFile;
      }else{
        return null;
      }
    }catch(error){
      print(error);
      return null;
    }
  }`

**Comment by AlexV525** [comment]
I wrote this without any IDEs so it's a pseudo-code:

```dart
Future<void> _handlePickedFile() async {
  File? _fileToBeHandle;
  await CameraPicker.pickFromCamera(
    context,
    pickerConfig: CameraPickerConfig(
      onEntitySaving: (BuildContext context, CameraPickerViewType viewType, File file) {
        _fileToBeHandle = file; // Pass the file out of the saving method's scope.
        Navigator.of(context)..pop()..pop(); // Should be popped twice to exit the picker.
      },
    ),
  );
  // Continue your custom flow here.
  print(_fileToBeHandle?.path);
}
```
