### ISSUE TITLE
[BUG] pad Camera magnifies

### ISSUE THREAD

**Issue by codercq** [fluttercandies/flutter_wechat_camera_picker#69]
When you open it landscape on an Android tablet, the camera magnifies, but the photos are fine

https://user-images.githubusercontent.com/17350596/149057518-4c9099fd-3787-4521-a4e8-9f3e2698ddc3.MOV

- Device: 小米pad5
- Package Version: [e.g. 2.6.3]
- Flutter Version: [e.g. v2.2.2]

**Comment by codercq** [comment]
the pad is lock landscape

**Comment by AlexV525** [comment]
I can't see anything from your video. Also, please submit issues according to requirement #31.
