### ISSUE TITLE
CameraPicker必须放在AssetPicker中使用吗？

### ISSUE THREAD

**Issue by ComexGit** [fluttercandies/flutter_wechat_camera_picker#7]
AlertOptionViewS01.show(
          context,
          title: '添加图片',
          actions: ["拍照", "手机相册"],
          cancelTitle: '取消',
          didSelectedAtIndex: (index, name) {
            print('index, name: ($index, $name)');
            if (index == 1) {
               CameraPicker.pickFromCamera(
                 context,
                 isAllowRecording: false,
               ).then((result) {
                print('assets: $assets');
               });

            } else if (index == 2) {
              AssetPicker.pickAssets(context).then((List<AssetEntity> assets) {
                print('assets: $assets');   
              });
            }
          },
        );
      },
    );

以上代码，AssetPicker可以跳转，CameraPicker无法跳转。
如示例demo中的代码，CameraPicker必须在AssetPicker中使用吗？

**Comment by AlexV525** [comment]
并不是，请检查 context。

**Comment by AlexV525** [comment]
如果有任何问题或是信息补充，请继续留言。
