### ISSUE TITLE
[BUG] 图片旋转问题

### ISSUE THREAD

**Issue by 1203556555** [fluttercandies/flutter_wechat_camera_picker#81]
**Describe the bug**
拍摄照片分辨率错误

**How to reproduce**
在oppo手机上，拍摄照片后返回的的宽高不正确，一张1080x1920的图片返回1920x1080，我怀疑在oppo上获取手机角度出现问题。

**Screenshots (If contains)**
![221646987119_ pic](https://user-images.githubusercontent.com/18067025/157830879-c2b52fbb-f645-4273-a673-0d52d66fd018.jpg)
![211646987118_ pic](https://user-images.githubusercontent.com/18067025/157830908-930852f6-6214-40da-a7b4-02910df5f5aa.jpg)

**Version information**

- Device: [e.g. OPPO K9s]
- OS: [e.g. ColorOS V11.2(Android 11)]
- Package Version: [e.g. 2.6.5]
- Flutter Version: [e.g. v2.8.1]

**Comment by AlexV525** [comment]
Code? Related screenshots?

**Comment by 1203556555** [comment]
code
final assets = await CameraPicker.pickFromCamera(context, imageFormatGroup: ImageFormatGroup.jpeg);

screenshots
![231646992059_ pic](https://user-images.githubusercontent.com/18067025/157843210-ed8eb70e-e544-480f-8bb9-1a1bad7f44e5.jpg)
![WX20220311-174655](https://user-images.githubusercontent.com/18067025/157843229-d6717ed5-36eb-46e2-962b-1cc46f5c8a26.png)

正常应该返回1080x1920

**Comment by AlexV525** [comment]
系统不是也提示的 1920x1080？该问题与 plugin 无关。

**Comment by 1203556555** [comment]
图片信息显示的也是1920x1080，但是使用系统相机拍摄就正常返回1080x1920

**Comment by AlexV525** [comment]
首先查看 `camera` 插件是否能复现。

**Comment by 1203556555** [comment]
在image_picker这个插件上拍摄的图片是正常的
