### ISSUE TITLE
How to user onEntitySaving feature?

### ISSUE THREAD

**Issue by GauravCalidig** [fluttercandies/flutter_wechat_camera_picker#83]
I dont want the video to be saved by default , anyone has any idea how can i use this code? it shows error.
![image](https://user-images.githubusercontent.com/90178033/160539237-0bd64468-d3af-439d-b75b-0a05d3cdd1a2.png)

**Comment by GauravCalidig** [comment]
There is no example related to this as well

**Comment by AlexV525** [comment]
#31
