### ISSUE TITLE
Not able to figure out how to use "onEntitySaving"

### ISSUE THREAD

**Issue by GauravCalidig** [fluttercandies/flutter_wechat_camera_picker#84]
Version information

Device: honor 8X
OS: ANDROID 10
Package Version: v3.0.2
Flutter Version: v2.10.3
 I am not able to figure out how to use onentitysaving,
I dont want the video to get saved to gallery
![image](https://user-images.githubusercontent.com/90178033/160545221-6136ca3e-0215-4f5d-835a-48cadf94466b.png)

**Comment by AlexV525** [comment]
I can't see the full error in your screenshot.

**Comment by GauravCalidig** [comment]
The parameter 'context' can't have a value of 'null' because of its type, but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier. @AlexV525

**Comment by GauravCalidig** [comment]
![image](https://user-images.githubusercontent.com/90178033/160554047-6dfeb6cc-f8f9-4b3e-a6f3-0aa23f8f8461.png)

**Comment by GauravCalidig** [comment]
@AlexV525 Thanks for the quick action, i hope it will get resolved by today

**Comment by AlexV525** [comment]
You can try with the PR and see if it resolves the issue.

**Comment by GauravCalidig** [comment]
Hi @AlexV525 , The Callback doenst triggers, its still saving the data in internal storage and onentitysaving doent gets called

![image](https://user-images.githubusercontent.com/90178033/160589835-42a6092e-7d92-43d5-a7d6-49dfdda37c93.png)

**Comment by GauravCalidig** [comment]
![image](https://user-images.githubusercontent.com/90178033/160590028-1aef77dd-0969-4331-a02c-16cdd7335478.png)
According to the documentation this should'nt happen

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/160591061-36b2c0bb-1853-40e9-bf3f-38362dde7ff4.png)

**Comment by gauravmehta13** [comment]
Can you check it for video once as well not sure why its not working
