### ISSUE TITLE
[BUG] Camera screen does not close when permission denied

### ISSUE THREAD

**Issue by anderscheow** [fluttercandies/flutter_wechat_camera_picker#95]
**Describe the bug**
Camera does not close when permission denied.

**How to reproduce**

1. Open camera by `CameraPicker.pickFromCamera`.
2. Wait for permission dialog to prompt
3. Select `Don't allow`
4. Camera screen stuck with black screen

**Screenshots (If contains)**

**Version information**

- Device: Any Android or iOS device
- OS: Any Android or iOS version
- Package Version: 3.1.0
- Flutter Version: 2.10.5

**Additional context**

**Comment by AlexV525** [comment]
This is intended, as we don't handle the permission exception internally. Please handle the exception in your code and pop the picker manually.
